### ISSUE TITLE
hotswapping mod

### ISSUE THREAD

**Issue by 0x42h** [draivin/rust-hotswap#6]
Would you like to
```rust
#[hotswap]
mod more_attractive;
```
?

**Comment by draivin** [comment]
I'm guessing you want to be able to hotswap all the functions inside a mod at once? Or maybe only the publicly available ones?

**Comment by 0x42h** [comment]
Well, actually, @draivin, I was already realizing this in the moment, but in that same moment of haste my subconsciousness got the best out of me, albeit I stand (self-)corrected; my motivation for the request was an attempt towards a solution to a problem that actually has to be solved differently. Please forgive me for wasting our time and energy.
